USE rom_data_collection;
CREATE TABLE ChatGPT4o_Finetune_Data (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PREVIOUS_TEXT TEXT,  
    CURRENT_TEXT TEXT,   
    MAPPING_DATA MEDIUMTEXT, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
